musicpro/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('shop/', views.ProductListView.as_view(), name='product-list'),
    path('shop/<slug>/', views.ProductDetailView.as_view(), name='product-detail'),
    path('carro-compras/', views.CartView.as_view(), name='summary'),
    path('aumentar-cantidad/<pk>/', views.IncreaseQuantityView.as_view(), name='increase-quantity'),
    path('reducir-cantidad/<pk>/', views.DecreaseQuantityView.as_view(), name='decrease-quantity'),
    path('remover-de-carro/<pk>/', views.RemoveFromCartView.as_view(), name='remove-from-cart'),
]  

musicpro/musicpro/urls.py
from django.contrib import admin
from django.urls.conf import include
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from core import views
from productos.views import ProductViewSet
from rest_framework import routers

# Create your views here.
router = routers.DefaultRouter()
router.register('productos', ProductViewSet)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomeView.as_view(), name='home'),
    path('api/', include(router.urls)),
    path('cart/', include('cart.urls', namespace='cart')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

musicpro/cart/models.py
from django.db import models
from django.db.models.deletion import CASCADE
from productos.models import Producto, Marca, Categoria
from django.contrib.auth import get_user_model

# Create your models here.
User = get_user_model()

class Address(models.Model):
    ADDRESS_CHOICES = (
        ('B', 'Billing'),
        ('S', 'Shipping'),
    )

    user = models.ForeignKey(User, on_delete=CASCADE)
    address_line_1 = models.CharField(max_length=150)
    address_line_2 = models.CharField(max_length=150)
    city = models.CharField(max_length=150)
    zipe_code = models.CharField(max_length=150)
    address_type = models.CharField(max_length=1, choices=ADDRESS_CHOICES)
    default = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.address_line_1}, {self.address_line_2}, {self.city}, {self.zipe_code}"

    class Meta:
        verbose_name_plural = 'Addresses'

class OrderItem(models.Model):
    order = models.ForeignKey('Order', related_name='items', on_delete=models.CASCADE)
    product = models.ForeignKey(Producto, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return f"{self.quantity} x {self.product.nombre}"
    
    def get_raw_total_item_price(self):
        return self.quantity * self.product.precio

    def get_total_item_price(self):
        price = self.get_raw_total_item_price() #1000
        return "{:.2f}".format(price / 100)

class Order(models.Model):
    user = models.ForeignKey(User,blank=True, null=True, on_delete=CASCADE)
    start_date = models.DateTimeField(auto_now_add=True)
    order_date = models.DateTimeField(blank=True, null=True)
    ordered = models.BooleanField(default=False)

    billing_address = models.ForeignKey(
        Address, related_name='billing_address', blank=True, null=True, on_delete=models.SET_NULL)
    shipping_address = models.ForeignKey(
        Address, related_name='shipping_address', blank=True, null=True, on_delete=models.SET_NULL)

    def __str__(self):
        return self.reference_number

    @property
    def reference_number(self):
        return f"ORDER-{self.pk}"

    def get_raw_subtotal(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.get_raw_total_item_price()
        return total

    def get_subtotal(self):
        subtotal = self.get_raw_subtotal()
        return "{:.2f}".format(subtotal / 100)

    def get_raw_total(self):
        subtotal = self.get_raw_subtotal()
        return subtotal

    def get_total(self):
        total = self.get_raw_total()
        return "{:.2f}".format(total / 100)

class Payment(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name='payments')
    payment_method = models.CharField(max_length=20, choices=(
        ('Paypal', 'Debito'),
    ))
    timestamp = models.DateTimeField(auto_now_add=True)
    succesful = models.BooleanField(default=False)
    amount = models.FloatField()
    raw_response = models.TextField()

    def __str__(self):
        return self.reference_number

    @property
    def reference_number(self):
        return f"PAYMENT-{self.order}-{self.pk}"

musicpro/cart/forms.py
from django import forms
from .models import OrderItem, Address
from productos.models import Producto
from django.contrib.auth import get_user_model

User = get_user_model()

class AddToCartForm(forms.ModelForm):
    quantity = forms.IntegerField(min_value=1)

    class Meta:
        model = OrderItem
        fields = ['quantity']

    def __init__(self, *args, **kwargs):
        self.product_id = kwargs.pop('product_id')
        product = Producto.objects.get(id=self.product_id)
        super().__init__(*args, **kwargs)

    def clean(self):
        product_id = self.product_id
        product = Producto.objects.get(id=self.product_id)
        quantity = self.cleaned_data['quantity']

        if product.stock < quantity:
            raise forms.ValidationError(f"The maximum stock is {product.stock}")



class AddressForm(forms.Form):
    
    shipping_address_line_1 = forms.CharField(required=False)
    shipping_address_line_2 = forms.CharField(required=False)
    shipping_zip_code = forms.CharField(required=False)
    shipping_city = forms.CharField(required=False)

    billing_address_line_1 = forms.CharField(required=False)
    billing_address_line_2 = forms.CharField(required=False)
    billing_zip_code = forms.CharField(required=False)
    billing_city = forms.CharField(required=False)

    selected_shipping_address = forms.ModelChoiceField(
        Address.objects.none(), required=False
    )

    selected_billing_address = forms.ModelChoiceField(
        Address.objects.none(), required=False
    )

    def __init__(self, *args, **kwargs):
        user_id = kwargs.pop('user_id')
        super().__init__(*args, **kwargs)

        user = User.objects.get(id=user_id)

        shipping_address_qs = Address.objects.filter(
            user=user,
            address_type='S'
        )

        billing_address_qs = Address.objects.filter(
            user=user,
            address_type='B'
        )

        self.fields['selected_shipping_address'].queryset = shipping_address_qs
        self.fields['selected_billing_address'].queryset = billing_address_qs


    def clean(self):
        data = self.cleaned_data

        selected_shipping_address = data.get('selected_shipping_address', None)
        if selected_shipping_address is None:
            if not data.get('shipping_address_line_1', None):
                self.add_error("shipping_address_line_1", "Please fill in this field")
            if not data.get('shipping_address_line_2', None):
                self.add_error("shipping_address_line_2", "Please fill in this field")
            if not data.get('shipping_zip_code', None):
                self.add_error("shipping_zip_code", "Please fill in this field")
            if not data.get('shipping_city', None):
                self.add_error("shipping_city", "Please fill in this field")

        selected_billing_address = data.get('selected_billing_address', None)
        if selected_billing_address is None:
            if not data.get('billing_address_line_1', None):
                self.add_error("billing_address_line_1", "Please fill in this field")
            if not data.get('billing_address_line_2', None):
                self.add_error("billing_address_line_2", "Please fill in this field")
            if not data.get('billing_zip_code', None):
                self.add_error("billing_zip_code", "Please fill in this field")
            if not data.get('billing_city', None):
                self.add_error("billing_city", "Please fill in this field")

musicpro/cart/views.py
from django.db.models.query_utils import Q
from django.shortcuts import render
from django.views import generic
from productos.models import Producto
from cart.models import OrderItem, Address, Payment, Order
from .forms import AddToCartForm, AddressForm
from .utils import get_or_set_order_session
from django.shortcuts import get_object_or_404, reverse, redirect


# Create your views here.
class ProductListView(generic.ListView):
    template_name = 'cart/product_list.html'
    queryset = Producto.objects.all()

class ProductDetailView(generic.FormView):
    template_name = 'cart/product_detail.html'
    form_class = AddToCartForm

    def get_object(self):
        return get_object_or_404(Producto, slug=self.kwargs["slug"])

    def get_success_url(self):
        return reverse("home")

    def get_form_kwargs(self):
        kwargs = super(ProductDetailView, self).get_form_kwargs()
        kwargs["product_id"] = self.get_object().id
        return kwargs

    def form_valid(self, form):
        order = get_or_set_order_session(self.request)
        product = self.get_object()

        item_filter = order.items.filter(product=product)

        if item_filter.exists():
            item = item_filter.first()
            item.quantity += int(form.cleaned_data['quantity'])
            item.save()

        else:
            new_item = form.save(commit=False)
            new_item.product = product
            new_item.order = order
            new_item.save()
        
        return super(ProductDetailView, self).form_valid(form)


    def get_context_data(self, **kwargs):
        context = super(ProductDetailView, self).get_context_data(**kwargs)
        context['product'] = self.get_object()

        return context

class CartView(generic.TemplateView):
    template_name = 'cart/cart.html'

    def get_context_data(self, *args, **kwargs):
        context = super(CartView, self).get_context_data(**kwargs)
        context["order"] = get_or_set_order_session(self.request)
        return context

class IncreaseQuantityView(generic.View):
    def get(self, request, *args, **kwargs):
        order_item = get_object_or_404(OrderItem, id=kwargs['pk'])
        order_item.quantity += 1
        order_item.save()
        return redirect("cart:summary")


class DecreaseQuantityView(generic.View):
    def get(self, request, *args, **kwargs):
        order_item = get_object_or_404(OrderItem, id=kwargs['pk'])

        if order_item.quantity <= 1:
            order_item.delete()
        else:
            order_item.quantity -= 1
            order_item.save()
        return redirect("cart:summary")

class RemoveFromCartView(generic.View):
    def get(self, request, *args, **kwargs):
        order_item = get_object_or_404(OrderItem, id=kwargs['pk'])
        order_item.delete()
        return redirect("cart:summary")

musicpro/templates/cart/cart.html
{% extends "base.html" %}

{% block content %}

<div class="bg-light py-3">
    <div class="container">
        <div class="row">
            <div class="col-md-12 mb-0">
                <a href={% url 'home' %}">Inicio</a>
                <span class="mx-2 mb-0">/</span>
                <strong class="text-block">Carro de compras</strong>
            </div>
        </div>
    </div>
</div>

<div class="site-section">
    <div class="container">
        <div class="row mb-5">

            <div class="col-md-12">
                <div class="site-blocks-table">
                    <table>
                        <thead>
                            <tr>
                                <th>Imagen</th>
                                <th>Producto</th>
                                <th>Precio</th>
                                <th>Cantidad</th>
                                <th>Total</th>
                                <th>Acción</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for item in order.items.all %}
                            <tr>
                                <td class="product-thumbnail">
                                    <a href="{{ product.get_absolute_url }}"><img src="{{ item.product.imagen.url }}" class="img-fluid"></a>
                                </td>
                                <td class="product-name">
                                    <a href="{{ product.get_absolute_url }}"><h2 class="h5 text-black">{{ item.product.nombre }}</h2></a>
                                </td>
                                <td>${{ item.product.get_price }}</td>
                                <td>
                                    <div class="input-group mb-3" style="max-width: 120px;">
                                        <div class="input-group-pretend">
                                            <a href="{% url 'cart:decrease-quantity' item.id %}" class="btn btn-outline-primary">
                                                &minus;
                                            </a>
                                        </div>
                                        <input type="text" class="form-control text-center"
                                        value="{{ item.quantity }}"
                                        >
                                        <div class="input-group-append">
                                            <a href="{% url 'cart:increase-quantity' item.id %}" class="btn btn-outline-primary">
                                                &plus;
                                            </a>
                                        </div>
                                    </div>
                                </td>
                                <td>
                                    ${{ item.get_total_item_price }}
                                </td>
                                <td>
                                    <a href="{% url 'cart:remove-from-cart' item.id %}" class="btn btn-primary btn-sm">x</a>
                                </td>
                            </tr>
                            {% empty %}
                            <tr>
                                <td colspan="6">
                                    No hay productos en el carro. <a href="{% url 'cart:product-list' %}">Continua comprando</a>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
            
        </div>

        {% if order.items.count > 0 %}
            <div class="row">
                <div class="col-md-6">
                    <div class="row mb-5">
                        <div class="col-md-12">
                            <a class="btn btn-outline-primary btn-sm btn-block"
                            href="{% url 'cart:product-list' %}">Continuar comprando</a>
                        </div>
                    </div>
                </div>

                <div class="col-md-6 pl-5">
                    <div class="row justify-content-end">
                        <div class="col-md-12">
                            <div class="row">
                                <div class="col-md-12 text-right border-bottom mb-5">
                                    <h3 class="text-black h4 text-uppercase">Total carro</h3>
                                </div>
                            </div>

                            <div class="row mb-3">
                                <div class="col-md-6">
                                    <span class="text-black">Subtotal</span>
                                </div>

                                <div class="col-md-6 text-right">
                                    <strong class="text-black">${{ order.get_subtotal }}</strong>
                                </div>
                            </div>

                            <div class="row mb-5">
                                <div class="col-md-6">
                                    <span class="text-black">Total</span>
                                </div>

                                <div class="col-md-6 text-right">
                                    <strong class="text-black">${{ order.get_total }}</strong>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-md-12">
                                    <a href="" class="btn btn-warning btn-lg py-3 btn-block">Continuar con pago</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        {% endif %}

    </div>
</div>


{% endblock content %}

musicpro/templates/cart/product_detail.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="bg-light py-3">
    <div class="container">
        <div class="row">
            <div class="col-md-12 mb-0">
                <a href={% url 'home' %}">Inicio</a>
                <span class="mx-2 mb-0">/</span>
                <strong class="text-block">{{ product.nombre}}</strong>
            </div>
        </div>
    </div>
</div>
<div class="site-section">
    <div class="container">
        <div class="row mb-5">
            <div class="col-md-6">
                <a href=""><img src="{{ product.imagen.url}}" alt="" class="img-fluid h-5 w-5"></a>
            </div>
            <div class="col-md-6 md-4" data-aos='fade-up'>
                <h2 class="text-black">{{ product.nombre }}</h2>
                <p class="mb-0">{{ product.descripcion }}</p>
                <p class="mt-2 fs-2 fw-bold">$ {{ product.precio }}</p>
                <p class="mt-2">Stock disponible: {{ product.stock }}</p>
                {% if product.in_stock %}
                    <form method="POST">
                        {% csrf_token %}
                        {{ form|crispy }}
                        <button type='submit' class="btn btn-sm btn-primary buy-now">Agregar al carro</button>
                    </form>
                {% else %}
                    <p>Producto fuera de stock</p>
                {% endif %}
            </div>
        </div>
    </div>
</div>
    
{% endblock content %}

musicpro/templates/cart/product_list.html
{% extends 'base.html' %}

{% block content %}
<div class="bg-light py-3">
    <div class="container">
        <div class="row">
            <div class="col-md-12 mb-0">
                <a href={% url 'home' %}">Inicio</a>
                <span class="mx-2 mb-0">/</span>
                <strong class="text-block">Productos</strong>
            </div>
        </div>
    </div>
</div>
<div class="site-section">
    <div class="container">
        <div class="row mb-5">
            {% for product in object_list %}
                <div class="col-lg-4 col-md-6 md-4" data-aos='fade-up'>
                    <figure class="block-4-image">
                        <a href="{{ product.get_absolute_url }}"><img src="{{ product.imagen.url}}" alt="" class="img-fluid h-5 w-5"></a>
                    </figure>
                    <div class="bloc-4-text p-4"></div>
                    <a href="{{ product.get_absolute_url }}">{{ product.nombre }}</a>
                    <p class="mb-0">$ {{ product.precio }}</p>
                </div>
            {% endfor %}
        </div>
    </div>
</div>
    
{% endblock content %}